// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Utilisateur connect\xE9",
  description: "Retourne l'identit\xE9 de l'utilisateur FastRelays connect\xE9 (id et email) pour v\xE9rifier la connexion.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const info = { userId: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-products.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
import { mockProducts } from "npm:@/data/businessMockData";
var list_products_default = defineTool2({
  name: "list_products",
  title: "Lister les produits",
  description: "Liste les produits de la boutique avec leur prix, stock et statut. Un filtre texte optionnel permet de chercher par nom ou cat\xE9gorie.",
  inputSchema: {
    search: z.string().optional().describe("Filtre texte sur le nom ou la cat\xE9gorie."),
    limit: z.number().int().optional().describe("Nombre maximum de produits retourn\xE9s (d\xE9faut 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const term = search?.trim().toLowerCase();
    const items = mockProducts.filter(
      (p) => !term ? true : `${p.name ?? ""} ${p.category ?? ""}`.toLowerCase().includes(term)
    ).slice(0, Math.max(1, Math.min(limit ?? 20, 100)));
    return {
      content: [{ type: "text", text: JSON.stringify(items) }],
      structuredContent: { count: items.length, products: items }
    };
  }
});

// src/lib/mcp/tools/list-orders.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { mockOrders } from "npm:@/data/businessMockData";
var list_orders_default = defineTool3({
  name: "list_orders",
  title: "Lister les commandes",
  description: "Liste les commandes de la boutique avec le client, le montant et le statut. Un filtre de statut optionnel est disponible.",
  inputSchema: {
    status: z2.string().optional().describe("Filtre exact sur le statut de la commande."),
    limit: z2.number().int().optional().describe("Nombre maximum de commandes retourn\xE9es (d\xE9faut 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const wanted = status?.trim().toLowerCase();
    const items = mockOrders.filter((o) => !wanted ? true : String(o.status ?? "").toLowerCase() === wanted).slice(0, Math.max(1, Math.min(limit ?? 20, 100)));
    return {
      content: [{ type: "text", text: JSON.stringify(items) }],
      structuredContent: { count: items.length, orders: items }
    };
  }
});

// src/lib/mcp/tools/list-order-messages.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";

// src/lib/mcp/tools/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.2";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}

// src/lib/mcp/tools/list-order-messages.ts
var list_order_messages_default = defineTool4({
  name: "list_order_messages",
  title: "Lire la messagerie d'une commande",
  description: "Retourne les messages \xE9chang\xE9s sur une commande, tri\xE9s du plus ancien au plus r\xE9cent.",
  inputSchema: {
    order_id: z3.string().min(1).describe("Identifiant de la commande.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("order_messages").select("*").eq("order_id", order_id).order("created_at", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { count: data?.length ?? 0, messages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/send-order-message.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var send_order_message_default = defineTool5({
  name: "send_order_message",
  title: "Envoyer un message sur une commande",
  description: "Envoie un message dans la messagerie d'une commande au nom de l'utilisateur connect\xE9.",
  inputSchema: {
    order_id: z4.string().min(1).describe("Identifiant de la commande."),
    content: z4.string().trim().min(1).describe("Contenu du message \xE0 envoyer."),
    sender_role: z4.enum(["seller", "buyer"]).optional().describe("R\xF4le de l'exp\xE9diteur (d\xE9faut: seller).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ order_id, content, sender_role }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("order_messages").insert({
      order_id,
      content,
      sender_role: sender_role ?? "seller",
      sender_name: ctx.getUserEmail() ?? "Utilisateur"
    }).select();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0]) }],
      structuredContent: { message: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sdawocslqhhtjalsgbde";
var mcp_default = defineMcp({
  name: "fastrelays-mcp",
  title: "FastRelays MCP",
  version: "0.1.0",
  instructions: "Outils FastRelays : consulter les produits et commandes de la boutique, lire et envoyer des messages sur une commande. Utilisez `whoami` pour v\xE9rifier l'utilisateur connect\xE9.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_products_default,
    list_orders_default,
    list_order_messages_default,
    send_order_message_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
